version: '3'
services:

  #PHP Service
  app:
    build:
      context: laravel
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    env_file:
      - ${PWD}/.env
    volumes:
      - ${PWD}/laravel:/var/www
      - ${PWD}/.env:/var/www/.env
      - vendor:/var/www/vendor
      - node_modules:/var/www/node_modules
    networks:
      - app-network
    depends_on:
      - db

  ##NodeJS - uncomment to enable websockets
  #sockets:
  #  build:
  #    context: node
  #    dockerfile: Dockerfile
  #  container_name: sockets
  #  ports:
  #    - "3000:3000"
  #  networks:
  #    - app-network
  #  depends_on:
  #    - app

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports: 
      - "80:80"
    volumes:
      - ./laravel/:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - db
      - app

  ##SSL-enabled Nginx Service; uncomment to use
  ##Make sure to comment out the above webserver block
  #webserver:
  #  image: ghcr.io/linuxserver/swag
  #  container_name: swag
  #  restart: unless-stopped
  #  environment:
  #    PUID: 1000
  #    PGID: 1000
  #    TZ: $TIMEZONE
  #    URL: $SITE_URL
  #    SUBDOMAINS: $SUBDOMAINS
  #    ONLY_SUBDOMAINS: $ONLY_SUBDOMAINS
  #    VALIDATION: http
  #    EMAIL: $EMAIL # optional
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - ./swag/site-confs:/config/nginx/site-confs
  #    - ./swag/fastcgi_params:/config/nginx/fastcgi_params
  #    - ./laravel/:/config/www
  #    - config:/config
  #  networks:
  #    - app-network
  #  depends_on:
  #    - db
  #    - app

  # MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql-files
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
    dbdata:
      driver: local
    vendor:
      driver: local
    node_modules:
      driver: local
    config:
      driver: local
