version: '3'
services:

  #PHP Service
  app:
    build:
      context: laravel
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - secret:/var/www/secrets/
      - ./laravel:/var/www
      - node:/usr/lib/node_modules
    networks:
      - app-network

  #NodeJS - uncomment for websockets
  sockets:
    build:
      context: node
      dockerfile: Dockerfile
    container_name: sockets
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - app

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - db
      - app

  #MySQL Service
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST_FILE: /var/secrets/host
      # We want to eventually have a separate field in .env for this
      MYSQL_ROOT_PASSWORD_FILE: /var/secrets/dbpass
      MYSQL_DATABASE_FILE: /var/secrets/database
      MYSQL_USER_FILE: /var/secrets/user
      MYSQL_PASSWORD_FILE: /var/secrets/dbpass
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - secret:/var/secrets/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - dbdata:/var/lib/mysql-files
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
    dbdata:
      driver: local
    secret:
      driver: local
    node:
      driver: local